<a href="https://colab.research.google.com/github/RioDeMilo/Data-analysis-with-python-projects/blob/main/Deviation_calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)



1.21.6


In [ ]:
 list = ([0,1,2,3,4,5,6,7,8])
Y = np.asarray(list)
X = Y.reshape(3,3)
 def calculate(array):
      return 'mean', array.mean(axis=0), array.mean(axis=1), array.mean(),'Variance', array.var(axis=0), array.var(axis=1), array.var(), 'Standart deviation', array.std(axis=0), array.std(axis=1), array.std(),'Max', array.max(axis=0), array.max(axis=1), array.max(), 'Min', array.min(axis=0), array.min(axis=1), array.min(), 'Sum', array.sum(axis=0), array.sum(axis=1), array.sum()
calculate(X)

('mean',
 array([3., 4., 5.]),
 array([1., 4., 7.]),
 4.0,
 'Variance',
 array([6., 6., 6.]),
 array([0.66666667, 0.66666667, 0.66666667]),
 6.666666666666667,
 'Standart deviation',
 array([2.44948974, 2.44948974, 2.44948974]),
 array([0.81649658, 0.81649658, 0.81649658]),
 2.581988897471611,
 'Max',
 array([6, 7, 8]),
 array([2, 5, 8]),
 8,
 'Min',
 array([0, 1, 2]),
 array([0, 3, 6]),
 0,
 'Sum',
 array([ 9, 12, 15]),
 array([ 3, 12, 21]),
 36)