<a href="https://colab.research.google.com/github/RioDeMilo/Data-analysis-with-python-projects/blob/main/Deviation_calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)



1.21.6


In [95]:
def calculate(list):
  if len(list) == 9:
    array =  np.array(list).reshape(3,3)
    return {'mean': [array.mean(axis=0), array.mean(axis=1), array.mean()],
              'Variance': [array.var(axis=0), array.var(axis=1), array.var()], 
              'Standart deviation': [array.std(axis=0), array.std(axis=1), array.std()],
              'Max': [array.max(axis=0), array.max(axis=1), array.max()], 
              'Min': [array.min(axis=0), array.min(axis=1), array.min()],
              'Sum': [array.sum(axis=0), array.sum(axis=1), array.sum()]}
  else : 
   print ('the list must contain 9 values')
   
calculate([2,6,2,8,4,0,1,5,7,9,8])

the list must contain 9 values


In [97]:
def calculate(list):# to get the list of the function i used array andd i returned error cuz the starting value it's a list
  if len(list) == 9: #I wanted to get a if function to start the programg if the list contained 9 values else will print the code error
    array = np.array(list).reshape(3,3) #it was required for the projecto to convert a list into a numpy array in a 3,3 form but now it does it in the start of the specified function
    return {'mean': [array.mean(axis=0), array.mean(axis=1), array.mean()], # the return value comes from the def function 
              'Variance': [array.var(axis=0), array.var(axis=1), array.var()], # all the return value iss contained in {} to get a final result of a dictionary
              'Standart deviation': [array.std(axis=0), array.std(axis=1), array.std()],# that's why every value conatins a index in this case strings like "mean" :
              'Max': [array.max(axis=0), array.max(axis=1), array.max()], # to contain multiple results in the values of the dictionary we separate with commmas
              'Min': [array.min(axis=0), array.min(axis=1), array.min()],
              'Sum': [array.sum(axis=0), array.sum(axis=1), array.sum()]}
  else : 
   print ('the list must contain 9 values')

   


the list must contain 9 values


In [84]:
print(calculate([2,6,2,8,4,0,1,5,7]))

None


In [28]:
dick = calculate([2,6,2,8,4,0,1,5,7])
type(dick['mean']) # with this test i proved that the result from the function calculate return a list and not a numpy array


list

In [29]:
calculate =  ([2,6,2,8,4,0,1,5,7])
array = np.array(calculate).reshape(3,3)
type(array)


numpy.ndarray

In [ ]:
np.array(10)
a= np.array(10)
type(a)

numpy.ndarray

In [ ]:
calculate = ([2,6,2,8,4,0,1,5,7])
array = np.array(calculate).reshape(3,3)
type(calculate),type(array)

(list, numpy.ndarray)

In [ ]:
X = [3, 4, 5]
print(X,type(X))
Y= np.array (X)
print(Y,type(Y))

[3, 4, 5] <class 'list'>
[3 4 5] <class 'numpy.ndarray'>


In [82]:
# here i'm trying to add the error when a list =! 9 is passed in the function and i'm using the != to pass a true value when something isn't equall
def calculate(list):
  if len(list) != 9:
    print('the list must contain 9 values')
  else :
    array =  np.array(list).reshape(3,3)# noticed i need to put in the conditional if or else the cha gnge in the list to a array and not at the start of the function
    return {'mean': [array.mean(axis=0), array.mean(axis=1), array.mean()],
              'Variance': [array.var(axis=0), array.var(axis=1), array.var()], 
              'Standart deviation': [array.std(axis=0), array.std(axis=1), array.std()],
              'Max': [array.max(axis=0), array.max(axis=1), array.max()], 
              'Min': [array.min(axis=0), array.min(axis=1), array.min()],
              'Sum': [array.sum(axis=0), array.sum(axis=1), array.sum()]} 
    
calculate([2,6,2,8,4,0,1,5,7])


{'mean': [array([3.66666667, 5.        , 3.        ]),
  array([3.33333333, 4.        , 4.33333333]),
  3.888888888888889],
 'Variance': [array([9.55555556, 0.66666667, 8.66666667]),
  array([ 3.55555556, 10.66666667,  6.22222222]),
  6.987654320987654],
 'Standart deviation': [array([3.09120617, 0.81649658, 2.94392029]),
  array([1.88561808, 3.26598632, 2.49443826]),
  2.6434171674156266],
 'Max': [array([8, 6, 7]), array([6, 8, 7]), 8],
 'Min': [array([1, 4, 0]), array([2, 0, 1]), 0],
 'Sum': [array([11, 15,  9]), array([10, 12, 13]), 35]}

In [ ]:
def tes(list): # i made this test to add the conditional to see if the list is masde out of 9 value sif its not the program will return a error
  if  len(list) == 9 : # i got to change the   list.count() == 9 : because ww need to know the total value and we do that with the len function
    return list, 'pass'
  else  :
    return'list is not 9 values'

In [ ]:
tes([2,6,2,8,4,0,1,5,7])

([2, 6, 2, 8, 4, 0, 1, 5, 7], 'pass')

In [ ]:
lista = ([2,6,2,8,4,0,1,5,7])
X =  np.array(lista).reshape(3,3)


AttributeError: ignored